displayName=Item Respawn Timer
author=JNCressey
description=Show timers for respawning items
tags=spawn,collecting,ironman,money making,money,making,telegrabbing,telekinetic grab,telekinetic,grab,herblore,secondary
plugins=com.itemrespawntimer.ItemRespawnTimerPlugin